baseURL = "https://localhost/" 
languageCode = "ja"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
title = "Yoshiaki's Blog"

hasCJKLanguage = true
enableEmoji = true

[permalinks]
  posts = "/posts/:slug/"
  pages = "/:slug/"

# pagination
[pagination]
  pagerSize = 6
  path = "page"

[languages]
[languages.ja]
  languageCode = "ja-JP"
  languageName = "日本語"
  weight = 1

[languages.en]
  languageCode = "en-US"
  languageName = "English"
  weight = 2

[languages."zh-cn"]
  languageCode = "zh-CN"
  languageName = "简体中文"
  weight = 3

[languages.fr]
  languageCode = "fr-FR"
  languageName = "Français"
  weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"

# Menus
[menus]

  # main
  [[menus.main]]
    name = "nav.posts"
    pageRef = "/posts"
    weight = 20
    [menus.main.params]
      icon = "posts"

  [[menus.main]]
    name = "nav.categories"
    pageRef = "/categories"
    weight = 30
    [menus.main.params]
      icon = "categories"

  [[menus.main]]
    name = "nav.tags"
    pageRef = "/tags"
    weight = 40
    [menus.main.params]
      icon = "tags"

  [[menus.main]]
    name = "nav.archives"
    pageRef = "/archives"
    weight = 50
    [menus.main.params]
      icon = "archive"

  # footer
  [[menus.footer]]
    name = "About"
    pageRef = "/about"
    weight = 10
    [menus.footer.params]
      icon = "about"

  [[menus.footer]]
    name = "Contact"
    url = "https://google.com"
    weight = 20
    [menus.footer.params]
      icon = "contact"

  [[menus.footer]]
    name = "RSS Feed"
    url = "/index.xml"
    weight = 30
    [menus.footer.params]
      icon = "rss"

  # social
  [[menus.social]]
    name = "GitHub"
    url = "https://github.com/username"
    weight = 10
    [menus.social.params]
      icon = "github"

  [[menus.social]]
    name = "Twitter"
    url = "https://twitter.com/username"
    weight = 20
    [menus.social.params]
      icon = "twitter"

  [[menus.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/username"
    weight = 30
    [menus.social.params]
      icon = "linkedin"

  [[menus.social]]
    name = "Email"
    url = "mailto:your.email@example.com"
    weight = 40
    [menus.social.params]
      icon = "email"

[params]
  # Basic site info with SEO
  description = "英語学習の効率を高めたい方へ。TOEFL・TOEIC・GRE対策や海外大学院進学に関する情報、実体験に基づいた勉強法やアドバイスを発信しています。"
  keywords = ["英語", "勉強", "TOEFL", "TOEIC", "GRE", "海外大学院"]
  defaultAuthor = "Yoshiaki Nozaki"
  language = "ja"
  shortName = "Hugo Narrow"
  images = ["images/og-default.avif"]

  [params.logo]
    image = "https://i.postimg.cc/VkdTrhGD/avatar.jpg"
    link = "/hugo-blog/"

  [params.favicon]
    svg = "https://i.postimg.cc/VkdTrhGD/avatar.jpg"

  [params.author]
    name = "Yoshiaki Nozaki"
    title = "Yoshiaki's Blog"
    description = "A personal blog sharing tips for studying"
    avatar = "https://i.postimg.cc/VkdTrhGD/avatar.jpg"

    [[params.author.social]]
      name = "GitHub"
      url  = "https://github.com/ny000815/hugo-blog/"
      icon = "github"

    [[params.author.social]]
      name = "Twitter"
      url  = "https://twitter.com/"
      icon = "twitter"

  # UI Components Control
  showThemeSwitch = true
  showDarkModeSwitch = true
  showLanguageSwitch = true
  languageSwitchMode = "dropdown"

  # Header sticky effect
  stickyHeader = true 

  # Dock display mode: "scroll", "always", "float"
  dock = "float"

  # default color scheme
  colorScheme = "default"

  [params.themes.default]
    name = "Default"
    order = 1
  [params.themes.claude]
    name = "Claude"
    order = 2
  [params.themes.bumblebee]
    name = "Bumblebee"
    order = 3
  [params.themes.emerald]
    name = "Emerald"
    order = 4
  [params.themes.nord]
    name = "Nord"
    order = 5
  [params.themes.sunset]
    name = "Sunset"
    order = 6
  [params.themes.abyss]
    name = "Abyss"
    order = 7
  [params.themes.dracula]
    name = "Dracula"
    order = 8
  [params.themes.amethyst]
    name = "Amethyst"
    order = 9
  [params.themes.slate]
    name = "Slate"
    order = 10
  [params.themes.twitter]
    name = "Twitter"
    order = 11

  [params.home]
    recentPostsCount = 5

  [params.post]
    showRelated = true
    relatedPostsCount = 3

    [params.post.license]
      show = true
      author = "Yoshiaki Nozaki"
      name = "CC BY-NC-SA 4.0"
      url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
      displayName = "CC BY-NC-SA 4.0"

  # comments
  [params.comments]
    enabled = true
    system = "giscus"

    [params.comments.giscus]
      repo = "ny000815/hugo-blog"
      repoId = "R_kgDOP5XvZg"
      category = "General"
      categoryId = "DIC_kwDOP5XvZs4CwEHC"
      mapping = "pathname"
      strict = "0"
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom"
      theme = "preferred_color_scheme"
      lang = "en"

  [params.analytics]
    enabled = true     

  [params.analytics.google]
    enabled = true 
    id = "G-R55FHM9685"

  [params.katex]
    enabled = true

    [[params.katex.delimiters]]
      left = "$$"
      right = "$$"
      display = true

    [[params.katex.delimiters]]
      left = "$"
      right = "$"
      display = false

    [[params.katex.delimiters]]
      left = "\\("
      right = "\\)"
      display = false

    [[params.katex.delimiters]]
      left = "\\["
      right = "\\]"
      display = true

  [params.mermaid]
    enabled = true

  # GLightbox
  [params.lightbox]
    enabled = false
    loop = true
    width = "80vw"
    height = "80vh"
    touchNavigation = true
    draggable = true
    zoomable = true
    preload = true
    descPosition = "bottom"

  # Justified Gallery
  [params.justified_gallery]
    enabled = false
    rowHeight = 300
    gutter = 30
    lastRow = "center"
    transitionDuration = "0.3s"
    resizeDebounce = 100
    rowHeightTolerance = 0.25
    maxRowsCount = 999999
    calculateItemsHeight = false

  [params.codeblock.collapse]
    enabled = true
    defaultState = "expanded" # expanded, collapsed
    autoCollapseLines = 30
    autoCollapseHeight = 400
    collapsedHeight = 120

  [params.readingProgress]
    enabled = true
    height = 3
    showOnHomepage = false
    smoothScroll = true
    hideOnComplete = false

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions.extras.delete]
    enable = true
  [markup.goldmark.extensions.extras.insert]
    enable = true
  [markup.goldmark.extensions.extras.mark]
    enable = true
  [markup.goldmark.extensions.extras.subscript]
    enable = false
  [markup.goldmark.extensions.extras.superscript]
    enable = false
  [markup.goldmark]
    strikethrough = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = "github"
    tabWidth = 2

[outputs]
  home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  baseName = "site"
  isPlainText = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"

  [[module.imports]]
    path = "github.com/tom2almighty/hugo-narrow"

